# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

from scrapy.item import Item, Field

class ChainItem(Item):
	owner_contractor = Field()
	name = Field()
	address = Field()
	telephone = Field()
	reference_number = Field()
	driving_dircetion_to_well = Field()
	date_completed = Field()
	well_use = Field()
	drilling_method = Field()
	pump_type = Field()
	depth = Field()
	pump_setting_depth = Field()
	water_quality = Field()
	casing_length = Field()
	casing_mateiral = Field()
	casing_diameter = Field()
	screen_length = Field()
	screen_material = Field()
	screen_diameter = Field()
	slot_size  = Field()
	type_of_test = Field()
	test_rate = Field()
	bail_test_rate = Field()
	drawdown = Field()
	static_water_level = Field()
	bailer_drawdown = Field()
	material = Field()
	depth_2 = Field()
	installation_method = Field()
	number_of_bags_used = Field()
	sealing_material = Field()
	well_abandonment_depth = Field()
	installation_method_2 = Field()
	number_of_bags_used_2 = Field()
	county = Field()
	township = Field()
	range = Field()
	section = Field()
	topo_map = Field()
	grant = Field()
	field_located_by = Field()
	field_located_on = Field()
	courthouse_location_by = Field()
	courthouse_location_on = Field()
	location_accepted_verification_by = Field()
	location_accepted_verification_on = Field()
	subdivision_name = Field()
	lot_number = Field()
	ft_w_of_el = Field()
	ft_n_of_sl = Field()
	ft_e_of_wl = Field()
	ft_s_of_nl = Field()
	ground_elevation = Field()
	depth_of_bedrock = Field()
	bedrock_elevation = Field()
	aquifer_elevation = Field()
	utm_easting = Field()
	utm_northing = Field()
	top = Field()
	bottom = Field()
	formation = Field()